<?php
require 'PHPMailer/src/PHPMailer.php'; 
require 'PHPMailer/src/SMTP.php'; 
require 'PHPMailer/src/Exception.php';
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;
use PHPMailer\PHPMailer\SMTP;

$nom = $_POST["nom"];
$mailp = $_POST["mail"];

$mail = new PHPMailer();

$mail->isSMTP();
$mail->Host = 'localhost';
$mail->SMTPAuth = false;
$mail->Username = '1a2b3c4d5e6f7g'; //paste one generated by Mailtrap
$mail->Password = '1a2b3c4d5e6f7g'; //paste one generated by Mailtrap
$mail->SMTPSecure = 'tls';
$mail->Port = 2525;

$mail->setFrom('noreply@mediamatique.ch', 'Mailtrap');
$mail->addReplyTo('noreply@mediamatique.ch', 'Mailtrap');
$mail->addAddress('$mailp', '$nom'); 

$mailContent = "<h1>Test</h1>
    <p>Hello.</p>";
$mail->Body = $mailContent;

if($mail->send()){
    echo 'Le mail a bien été envoyé.';
}else{
    echo 'Le mail a pas pu être envoyé.';
    echo 'Mailer Error: ' . $mail->ErrorInfo;
}
?>